schema_version = "1.0.0"

id = "crops_dataset_lsystem_extension"
version = "1.0.0"
name = "Crops Dataset L-System Extension"
tagline = "Allows rendering of Plant L-Systems"
maintainer = "abartc@ethz.ch"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

platforms = ["windows-x64", "linux-x64"]
wheels = [
    "./wheels/numpy-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/numpy-2.2.3-cp311-cp311-win_amd64.whl",
    "./wheels/scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/scipy-1.15.2-cp311-cp311-win_amd64.whl",
    "./wheels/tqdm-4.67.1-py3-none-any.whl",
    "./wheels/pillow-11.1.0-cp311-cp311-win_amd64.whl",
    "./wheels/pillow-11.1.0-cp311-cp311-manylinux_2_28_x86_64.whl"
]

[permissions]
files = "Save rendered images and additional information on disk"

[build]
paths_exclude_pattern = ["__pycache__/", ".*", "*.zip", "*.sh"]
